import React, { createContext, useContext, useEffect, useState } from 'react';

// Language dictionary for translation
const LANGS: Record<string, Record<string, string>> = {  en: {
    home: 'Home',
    orders: 'Orders',
    pos: 'POS',
    receipts: 'Receipts',
    settings: 'Settings',
    dashboard: 'Dashboard',
    management: 'Management',
    system: 'Point of Sale System',
    loading: 'Loading...',
    total: 'Total',
    pending: 'Pending',
    delivered: 'Delivered',
    search: 'Search',
    filter: 'Filter',
    save: 'Save',
    cancel: 'Cancel',
    confirm: 'Confirm',
    delivery: 'Delivery',
    customer: 'Customer',
    payment: 'Payment',
    username: 'Username',
    email: 'Email',
    role: 'Role',
    branch: 'Branch',
    cashier: 'Cashier',
    profile: 'Profile Information',
    theme: 'Theme',
    language: 'Language',
    notifications: 'Notifications',
    printer: 'Printer Settings',
    logout: 'Log out',
    // Home page translations
    welcomeToSteakz: 'Welcome to STEAKZ',
    exquisiteDining: 'Exquisite Dining Experience',
    welcomeSubtext: 'Discover exceptional flavors and unforgettable moments at our premium restaurant',
    viewMenu: 'View Menu',
    findLocation: 'Find Location',
    aboutRestaurant: 'About Our Restaurant',
    aboutText: 'At STEAKZ Restaurant, we pride ourselves on serving exceptional cuisine crafted from the finest ingredients. Our passionate chefs create memorable dining experiences that bring people together.',
    featuredDishes: 'Featured Dishes',
    viewFullMenu: 'View Full Menu',
    customerReviews: 'Customer Reviews',    // Menu page translations
    ourMenu: 'Our Menu',
    menuSubtext: 'Discover our delicious selection of dishes crafted with the finest ingredients',
    category: 'Category',
    allCategories: 'All Categories',
    searchDishes: 'Search dishes...',
    addToCart: 'Add to Cart',
    viewCart: 'View Cart',
    available: 'Available',
    unavailable: 'Unavailable',
    errorLoadingMenu: 'Error loading menu',
    shoppingCart: 'Shopping Cart',
    yourCartIsEmpty: 'Your cart is empty',
    selectPaymentMethod: 'Select payment method',
    cash: 'Cash',
    creditCard: 'Credit Card',
    debitCard: 'Debit Card',
    mobilePayment: 'Mobile Payment',    placeOrder: 'Place Order',
    placingOrder: 'Placing order...',    // NotFound page translations
    pageNotFound: 'Page Not Found',
    pageNotFoundDesc: 'Sorry, the page you are looking for does not exist or has been moved.',
    backToHome: 'Back to Home',
    // Login page translations
    login: 'Login',
    loginDesc: 'Welcome back! Please enter your details.',
    emailOrUsername: 'Email or Username',
    password: 'Password',
    forgotPassword: 'Forgot password?',
    signIn: 'Sign in',
    orContinueWith: 'Or continue with',
    google: 'Google',
    apple: 'Apple',
    dontHaveAccount: "Don't have an account?",
    signUp: 'Sign up',
    backToWebsite: 'Back to website',
    welcomeTo: 'Welcome to',
    brand: 'STEAKZ',
    capturingMoments: 'Capturing Moments,',
    creatingMemories: 'Creating Memories',
    loginFailed: 'Login failed',
    // Orders page translations
    restaurantOrders: 'Restaurant Orders',
    ordersSubtitle: 'Monitor and manage all customer orders in real-time',
    searchPlaceholder: 'Search by order ID or customer...',
    allOrders: 'All Orders',
    preparing: 'Preparing',
    ready: 'Ready',
    cancelled: 'Cancelled',
    orderNumber: 'Order',
    items: 'Items',
    status: 'Status',
    deliveryAddress: 'Delivery Address',
    orderTime: 'Order Time',
    paymentMethod: 'Payment',
    noOrders: 'No orders found',
    noOrdersDesc: 'Orders will appear here as customers place them.',
    loadingOrders: 'Loading orders...',
    errorLoading: 'Error loading orders',    viewDetails: 'View Details',
    updateStatus: 'Update Status',
    // MyOrders page translations
    myOrdersTitle: 'My Orders',
    myOrdersSubtitle: 'Track your order history and current deliveries',
    orderedAt: 'Ordered',
    noOrdersYet: 'No orders yet',
    noOrdersYetDesc: 'You haven\'t placed any orders yet.',
    browseMenu: 'Browse our menu to place your first order!',
    loginRequired: 'You must be logged in as a customer to view orders.',    trackOrder: 'Track Order',
    reorder: 'Order Again',
    // CreatePost page translations
    createPost: 'Create Post',
    title: 'Title',
    content: 'Content',    creating: 'Creating...',
    failedToCreatePost: 'Failed to create post',
    // Footer translations
    openingHours: 'Opening Hours',
    mondayFriday: 'Monday - Friday: 11:00 AM - 11:00 PM',
    saturdaySunday: 'Saturday - Sunday: 10:00 AM - 12:00 AM',
    contact: 'Contact',
    location: 'Location',    allRightsReserved: '© 2024 STEAKZ Restaurant. All rights reserved.',
    mainLocation: 'STEAKZ Main Location',
    // Locations section translations
    visitOurLocations: 'Visit Our Locations',
    findNearestRestaurant: 'Find your nearest STEAKZ Restaurant and make a reservation today.',
    findLocations: 'Find Locations',    // Branches page translations
    ourBranches: 'Our Branches',
    branchesSubtext: 'Find the branch nearest to you. Click on the map icon to see the location on Google Maps.',
    address: 'Address',
    phone: 'Phone',
    manager: 'Manager',
    viewOnMap: 'View on map',
    call: 'Call',
    // Inventory page translations
    inventory: 'Inventory',
    inventoryDescription: 'Manage and monitor stock levels for all ingredients and supplies',
    loadingInventory: 'Loading inventory...',
    allItems: 'All Items',
    lowStock: 'Low Stock',
    outOfStock: 'Out of Stock',
    inStock: 'In Stock',
    item: 'Item',
    quantity: 'Quantity',
    lastUpdated: 'Last Updated',
    noInventoryItems: 'No inventory items found',
    noLowStockItems: 'No low stock items',
    noOutOfStockItems: 'No out of stock items',
    menuItems: 'Menu Items',
    preferences: 'Preferences'
  },
  es: {
    home: 'Inicio',
    orders: 'Pedidos',
    pos: 'TPV',
    receipts: 'Recibos',
    settings: 'Configuración',
    dashboard: 'Panel',
    management: 'Gestión',
    system: 'Sistema de Punto de Venta',
    loading: 'Cargando...',
    total: 'Total',
    pending: 'Pendiente',
    delivered: 'Entregado',
    search: 'Buscar',
    filter: 'Filtrar',
    save: 'Guardar',
    cancel: 'Cancelar',
    confirm: 'Confirmar',
    delivery: 'Entrega',
    customer: 'Cliente',
    payment: 'Pago',
    username: 'Usuario',
    email: 'Correo',
    role: 'Rol',
    branch: 'Sucursal',
    cashier: 'Cajero',
    profile: 'Información de Perfil',
    theme: 'Tema',
    language: 'Idioma',
    notifications: 'Notificaciones',
    printer: 'Ajustes de Impresora',
    logout: 'Cerrar sesión'
  },
  fr: {
    home: 'Accueil',
    orders: 'Commandes',
    pos: 'PDV',
    receipts: 'Reçus',
    settings: 'Paramètres',
    dashboard: 'Tableau de bord',
    management: 'Gestion',
    system: 'Système Point de Vente',
    loading: 'Chargement...',
    total: 'Total',
    pending: 'En attente',
    delivered: 'Livré',
    search: 'Rechercher',
    filter: 'Filtrer',
    save: 'Enregistrer',
    cancel: 'Annuler',
    confirm: 'Confirmer',
    delivery: 'Livraison',
    customer: 'Client',
    payment: 'Paiement',
    username: 'Nom d\'utilisateur',
    email: 'Email',
    role: 'Rôle',
    branch: 'Branche',
    cashier: 'Caissier',
    profile: 'Informations du Profil',
    theme: 'Thème',
    language: 'Langue',
    notifications: 'Notifications',
    printer: 'Paramètres Imprimante',
    logout: 'Se déconnecter'
  },
  de: {
    home: 'Startseite',
    orders: 'Bestellungen',
    pos: 'Kasse',
    receipts: 'Belege',
    settings: 'Einstellungen',
    dashboard: 'Dashboard',
    management: 'Verwaltung',
    system: 'Kassensystem',
    loading: 'Laden...',
    total: 'Gesamt',
    pending: 'Ausstehend',
    delivered: 'Geliefert',
    search: 'Suchen',
    filter: 'Filtern',
    save: 'Speichern',
    cancel: 'Abbrechen',
    confirm: 'Bestätigen',
    delivery: 'Lieferung',
    customer: 'Kunde',
    payment: 'Zahlung',
    username: 'Benutzername',
    email: 'E-Mail',
    role: 'Rolle',
    branch: 'Filiale',
    cashier: 'Kassierer',
    profile: 'Profilinformationen',
    theme: 'Thema',
    language: 'Sprache',
    notifications: 'Benachrichtigungen',    printer: 'Druckereinstellungen',
    logout: 'Abmelden'
  },
  fa: {
    home: 'خانه',
    orders: 'سفارش‌ها',
    pos: 'صندوق فروش',
    receipts: 'رسید‌ها',
    settings: 'تنظیمات',
    dashboard: 'داشبورد',
    management: 'مدیریت',
    system: 'سیستم صندوق',
    loading: 'درحال بارگذاری...',
    total: 'مجموع',
    pending: 'در انتظار',
    delivered: 'تحویل داده شده',
    search: 'جستجو',
    filter: 'فیلتر',
    save: 'ذخیره',
    cancel: 'انصراف',
    confirm: 'تایید',
    delivery: 'تحویل',
    customer: 'مشتری',
    payment: 'پرداخت',
    username: 'نام کاربری',
    email: 'ایمیل',
    role: 'نقش',
    branch: 'شعبه',
    cashier: 'صندوقدار',
    profile: 'پروفایل',
    theme: 'تم',
    language: 'زبان',
    notifications: 'اطلاعات',
    printer: 'تنظیمات چاپگر',
    logout: 'خروج',
    welcomeToSteakz: 'خوش آمدید به STEAKZ',
    exquisiteDining: 'تجربه آشپزی عالی',
    welcomeSubtext: 'طعم‌های عالی و لحظات فراموش‌نشدنی در رستوران اپتیمال ما را کشف کنید',
    viewMenu: 'مشاهده منو',
    findLocation: 'یافتن مکان',
    aboutRestaurant: 'درباره رستوران ما',
    aboutText: 'در رستوران STEAKZ ما از ارائه غذای فوق‌العاده ساخته شده از بهترین مواد اولیه افتخار می‌کنیم. آشپزهای پرشور ما تجارب غذایی فراموش‌نشدنی را خلق می‌کنند که مردم را کنار هم می‌آورد.',
    featuredDishes: 'غذاهای ویژه',
    viewFullMenu: 'مشاهده منوی کامل',
    customerReviews: 'نقدهای مشتری',
    ourMenu: 'منوی ما',
    menuSubtext: 'انتخاب لذیذ غذاهایی را که با بهترین مواد اولیه درست شده‌اند کشف کنید',
    category: 'دسته',
    allCategories: 'تمام دسته‌ها',
    searchDishes: 'جستجو غذاها...',
    addToCart: 'افزودن به سبد',
    viewCart: 'مشاهده سبد',
    available: 'موجود',
    unavailable: 'موجود نیست',
    errorLoadingMenu: 'خطا در بارگذاری منو',
    shoppingCart: 'سبد خریدشما',
    yourCartIsEmpty: 'سبد خریدتان خالی است',
    selectPaymentMethod: 'انتخاب روش پرداخت',
    cash: 'نقد',
    creditCard: 'کارت اعتباری',
    debitCard: 'کارت خصوصی',
    mobilePayment: 'پرداخت موبایلی',
    placeOrder: 'ثبت سفارش',
    placingOrder: 'درحال ثبت سفارش...',
    pageNotFound: 'صفحه پیدا نشد',
    pageNotFoundDesc: 'متأسفانه، صفحه‌ای که دنبال می‌گردید وجود ندارد یا جابه‌جا شده‌است.',
    backToHome: 'بازگشت به خانه',
    login: 'ورود',
    loginDesc: 'خوش آمدید! لطفاً اطلاعاتتان را وارد کنید.',
    emailOrUsername: 'ایمیل یا نام کاربری',
    password: 'رمز عبور',
    forgotPassword: 'رمز عبور را فراموش کرده‌اید؟',
    signIn: 'ورود',
    orContinueWith: 'یا ادامه دهید با',
    google: 'Google',
    apple: 'Apple',
    dontHaveAccount: 'حساب ندارید؟',
    signUp: 'ثبت نام',
    backToWebsite: 'بازگشت به وبسایت',
    welcomeTo: 'خوش آمدید به',
    brand: 'STEAKZ',
    capturingMoments: 'ثبت لحظات،',
    creatingMemories: 'ایجاد خاطرات',
    loginFailed: 'ورود ناموفق',
    restaurantOrders: 'سفارش‌های رستوران',
    ordersSubtitle: 'نظارت و مدیریت تمام سفارش‌های مشتری به‌صورت بلادرنگ',
    searchPlaceholder: 'جستجوی ID سفارش یا مشتری...',
    allOrders: 'تمام سفارش‌ها',
    preparing: 'درحال آماده‌سازی',
    ready: 'آماده',
    cancelled: 'لغو‌شده',
    orderNumber: 'سفارش',
    items: 'اقلام',
    status: 'وضعیت',
    deliveryAddress: 'آدرس تحویل',
    orderTime: 'زمان سفارش',
    paymentMethod: 'روش پرداخت',
    noOrders: 'سفارشی پیدا نشد',
    noOrdersDesc: 'سفارش‌ها زمانی که مشتریان آن‌ها را ثبت کنند در اینجا نمایش داده می‌شوند.',
    loadingOrders: 'درحال بارگذاری سفارش‌ها...',
    errorLoading: 'خطا در بارگذاری سفارش‌ها',
    viewDetails: 'مشاهده جزئیات',
    updateStatus: 'به‌روز رسانی وضعیت',
    myOrdersTitle: 'سفارش‌های من',
    myOrdersSubtitle: 'تاریخچه سفارش و تحویل فعلی خود را ردیابی کنید',
    orderedAt: 'سفارش شده',
    noOrdersYet: 'هنوز سفارشی ثبت نشده‌است',
    noOrdersYetDesc: 'شما هنوز سفارشی ثبت نکرده‌اید.',
    browseMenu: 'منو را مرور کنید تا اولین سفارشتان را ثبت کنید!',
    loginRequired: 'برای مشاهده سفارش‌ها باید به‌عنوان مشتری وارد شوید.',
    trackOrder: 'ردیابی سفارش',
    reorder: 'سفارش دوباره',
    createPost: 'ایجاد پست',
    title: 'عنوان',
    content: 'محتوا',
    creating: 'درحال ایجاد...',
    failedToCreatePost: 'ایجاد پست ناموفق',
    openingHours: 'ساعات کاری',
    mondayFriday: 'دوشنبه - جمعه: 11:00 - 23:00',
    saturdaySunday: 'شنبه - یکشنبه: 10:00 - 00:00',
    contact: 'تماس',
    location: 'مکان',
    allRightsReserved: '© 2024 STEAKZ Restaurant. تمام حقوق محفوظ است.',
    mainLocation: 'دفتر مرکزی STEAKZ',
    visitOurLocations: 'از رستوران‌های ما بازدید کنید',
    findNearestRestaurant: 'نزدیک‌ترین رستوران STEAKZ خود را پیدا کنید و امروز یک میز رزرو کنید.',
    findLocations: 'یافتن رستوران‌ها',
    ourBranches: 'شعب‌های ما',
    branchesSubtext: 'شعبه‌ای نزدیک به خود را پیدا کنید. برای مشاهده مکان در Google Maps روی آیکون نقشه کلیک کنید.',
    address: 'آدرس',
    phone: 'تلفن',
    manager: 'مدیر',
    viewOnMap: 'مشاهده روی نقشه',
    call: 'تماس',
    inventory: 'انبار',
    inventoryDescription: 'مدیریت و نظارت سطح انبار برای تمام مواد اولیه و لوازم',
    loadingInventory: 'درحال بارگذاری انبار...',
    allItems: 'تمام اقلام',
    lowStock: 'انبار کم',
    outOfStock: 'تمام شده',
    inStock: 'موجود در انبار',
    item: 'قلم',
    quantity: 'مقدار',
    lastUpdated: 'آخرین به‌روز رسانی',
    noInventoryItems: 'هیچ قلم انبار پیدا نشد',
    noLowStockItems: 'هیچ قلمی با انبار کم',
    noOutOfStockItems: 'هیچ قلمی تمام نشده‌است',
    menuItems: 'اقلام منو',
    preferences: 'تنظیمات'
  }
};

export interface Settings {
  theme: 'light' | 'dark';
  language: string;
  currency: string;
  notifications: boolean;
  autoLogout: number;
  printerSettings: {
    defaultPrinter: string;
    copies: number;
    paperSize: string;
  };
}

const defaultSettings: Settings = {
  theme: (localStorage.getItem('theme') as 'light' | 'dark') || 'light',
  language: localStorage.getItem('language') || 'en',
  currency: localStorage.getItem('currency') || 'EUR',
  notifications: localStorage.getItem('notifications') !== 'false',
  autoLogout: parseInt(localStorage.getItem('autoLogout') || '30'),
  printerSettings: JSON.parse(localStorage.getItem('printerSettings') || '{"defaultPrinter":"Receipt Printer 01","copies":1,"paperSize":"A4"}')
};

export const SettingsContext = createContext<{
  settings: Settings;
  setSettings: React.Dispatch<React.SetStateAction<Settings>>;
  t: (key: string) => string;
} | undefined>(undefined);

export const SettingsProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [settings, setSettings] = useState<Settings>(defaultSettings);

  const t = (key: string) => LANGS[settings.language]?.[key] || key;
  useEffect(() => {
    document.body.className = settings.theme;
    localStorage.setItem('theme', settings.theme);
    localStorage.setItem('language', settings.language);
    localStorage.setItem('currency', settings.currency);
    localStorage.setItem('notifications', settings.notifications.toString());
    localStorage.setItem('autoLogout', settings.autoLogout.toString());
    localStorage.setItem('printerSettings', JSON.stringify(settings.printerSettings));
    window.dispatchEvent(new CustomEvent('app-settings-changed', {
      detail: {
        language: settings.language,
        currency: settings.currency
      }
    }));
  }, [settings]);

  return (
    <SettingsContext.Provider value={{ settings, setSettings, t }}>
      {children}
    </SettingsContext.Provider>
  );
};

export const useSettings = () => {
  const ctx = useContext(SettingsContext);
  if (!ctx) throw new Error('useSettings must be used within SettingsProvider');
  return ctx;
};